### ISSUE TITLE
File Not Found Error in CloudWatch Logs

### ISSUE THREAD

**Issue by fwang2000** [aws-samples/sagemaker-serverless-inference-benchmarking#2]
When I try to run a processing job using the Serverless Inference Benchmarking tool, I run into this error: FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/processing/input/data\invoke_args_examples.pkl'.

When I follow my S3 bucket where the input/ folder is, it has the invoke_args_examples.pkl in an input_1/ subfolder rather than data/ as shown below.

![image](https://github.com/aws-samples/sagemaker-serverless-inference-benchmarking/assets/61210395/146783aa-37b0-4c07-bee6-edd09169142b)

In the code I see that the input path is `sm_job_input_dir = "/opt/ml/processing/input/data"` so I'm not sure how to fix it.

I followed the tensorflow example in this repo.

```
example_invoke_file = convert_invoke_args_to_pkl(example_invoke_args)

processor = run_as_sagemaker_job(
    role=role,
    model_name=MODEL_NAME,
    invoke_args_examples_file= example_invoke_file,
    concurrency_benchmark_max_conc=[1, 10, 100]
)

print(
    f"Once the job is finished, the outputs will be uploaded to {processor.latest_job.outputs[0].destination}"
)
```

I believe I need to change the folder to run the tool properly but I'm not sure how to do so.

**Comment by szamarin** [comment]
Hi @fwang2000 Thanks for trying the tool. Did you run the notebook in Windows? The issue looks like I was using os.path.join to join the input data path `/opt/ml/processing/input/data` with the sample payload file `invoke_args_examples.pkl`. So when you ran the notebook in Windows it joins paths using a backslash rather than a forward slash. I've fixed the issue and you should be able to run it now.

**Comment by fwang2000** [comment]
Yes, thank you! Everything is working as expected now.
